[package]
name = "my-first-lib"
version = "0.1.0"
authors = ["peshwar9"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mymain"
path = "src/mymain.rs"

[lib]
crate-type = ["dylib"]


[dependencies]
